name: main
on:
  push:
    branches: [main]
  schedule:
  - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    - run: pip install httpx
    - run: git config --global user.name 'Github Actions'
    - run: git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
    - run: python update.py
    # - run: |
    #     git remote set-url origin https://x-access-token:$GH_TOKEN@github.com/$GITHUB_REPOSITORY
    #     git push origin HEAD:refs/heads/main --tags
    #   env:
    #     GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
