name: main
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    name: main
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set Git config
        run: |
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
      - uses: astral-sh/setup-uv@v4
        with:
          cache-dependency-glob: update.py
          enable-cache: true
      - name: Check for updates
        run: uv run update.py
